name: Generate an unique build key
on: [workflow_dispatch]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
             - name: Checkout
               uses: actions/checkout@v4
             - name: Build kyes
               run: |
                wget https://downloads.openwrt.org/snapshots/targets/qualcommax/ipq807x/openwrt-imagebuilder-qualcommax-ipq807x.Linux-x86_64.tar.xz
                tar -xf openwrt-imagebuilder-qualcommax-ipq807x.Linux-x86_64.tar.xz
                cd openwrt-imagebuilder-qualcommax-ipq807x.Linux-x86_64
                make image PROFILE=dynalink_dl-wrx36
                mkdir key
                mv key-build key/
                mv key-build.pub key/
             - name: Release build artifacts
               uses: ncipollo/release-action@v1.14.0
               with:
                 allowUpdates: true
                 draft: true
                 name: Build Key
                 tag: key
                 token: ${{ secrets.GITHUB_TOKEN }}
                 artifacts: openwrt-imagebuilder-qualcommax-ipq807x.Linux-x86_64/key/*
